services:
  postgres:
    image: postgres:16
    container_name: medstock-postgres
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medstock

    volumes:
      - medstock_pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: medstock-web
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/medstock?schema=public"
      NODE_ENV: development

    depends_on:
      - postgres

    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

    command: sh -c "npx prisma generate && npm run dev"

volumes:
  medstock_pgdata:
